mssqldef: support index
k0kubun/sqldef pull request #126
Opened 2021-06-21 06:13 UTC by ytakaya

This change supports the following features.
- ADD INDEX
- DROP INDEX

2021-06-21 21:11 UTC, k0kubun commented on schema/generator.go
> +			case GeneratorModeMssql:
This is applicable to all of your patches, but please consider NOT to introduce `g.mode` to a place where `g.mode` switch is not used. At least I couldn't understand why you needed to exclude `areSameIndexOptions` from `areSameIndexes`, and using a name like `generateDDLForCreateIndex` only for mssql is pretty confusing while you already have `generateIndexDefinition` for the same purpose.

2021-06-21 21:15 UTC, k0kubun requested changes
May I see your effort to reduce the number of new branches for `GeneratorModeMssql` first? Feel free to modify existing implementations for doing so.

I'm not saying you must not use `g.mode` switch everywhere. The general idea is that you should use `g.mode` switches preferably in deeply nested function calls rather than more abstract functions that already do a lot more things (e.g. `generateDDLsForCreateTable`). For example, if you generate entire DDLs from `generateIndexDefinition`, you could move a `g.mode` switch from `generateDDLsForCreateTable` to `generateIndexDefinition`.

The reason why I'm suggesting these changes is that first of all, ideally, every `g.mode` switch should be eliminated. But if you need to introduce it, you should consider introducing it to a trivial location that doesn't really impact an overall code flow or readability. As I said in the above comment, your current patch duplicates a function with similar roles, branches them in a relatively abstract place, and makes it hard to understand what is used by which mode.

2021-06-22 00:43 UTC, ytakaya commented
I apologize for the lack of explanation of the changes I made.
The following are the reasons why I needed `g.mode`.

In mssql, I couldn't use the syntax `ALTER TABLE` to put an index on an existing table, I had to use the syntax `CREATE INDEX`.
My addition of `generateDDLForCreateTable` is a function for the syntax `CREATE TABLE`. I made it a separate function because I thought its intent was different from the existing `generateIndexDefinition` for `ALTER TABLE`.
https://docs.microsoft.com/en-us/sql/t-sql/statements/alter-table-transact-sql?view=sql-server-2017#syntax-for-disk-based-tables

As for `areSameIndexOptions`, it was a branch born of my misunderstanding.
The syntax for the INDEX option existed in the existing parser.y, but it was not used in the generator.
Therefore, I mistakenly thought that DBs other than mssql were intentionally designed not to compare index options.

For these reasons, I thought that `areSameIndexOptions` should be removed, but what do you think should be done about `generateDDLsForCreateTable`?

2021-06-22 00:50 UTC, k0kubun commented
I knew you need `g.mode` for `ALTER TABLE`/`CREATE INDEX`. I'm just talking about where you use it. You should be able to have only one of `generateDDLForCreateIndex` and `generateIndexDefinition` and let it switch `ALTER TABLE` or `CREATE INDEX` using `g.mode` in it.

2021-06-22 00:53 UTC, ytakaya commented
I apologize for the lack of explanation of the changes I made. The following are the reasons why I needed g.mode.

In mssql, I couldn't use the syntax ALTER TABLE to put an index on an existing table, I had to use the syntax CREATE INDEX. My addition of generateDDLForCreateTable is a function for the syntax CREATE TABLE. I made it a separate function because I thought its intent was different from the existing generateIndexDefinition for ALTER TABLE. https://docs.microsoft.com/en-us/sql/t-sql/statements/alter-table-transact-sql?view=sql-server-2017#syntax-for-disk-based-tables

As for areSameIndexOptions, it was a branch born of my misunderstanding. The syntax for the INDEX option existed in the existing parser.y, but it was not used in the generator. Therefore, I mistakenly thought that DBs other than mssql were intentionally designed not to compare index options.

As you pointed out, I think that `areSameIndexOptions` should be removed, and for `generateDDLsForCreateTable`, putting the branch in an abstract place was not an optimal change.
Thank you for pointing this out, I'll try to fix it to improve the readability of the code.

2021-06-22 03:55 UTC, k0kubun commented
Not sure why you re-posted the comment, but https://github.com/k0kubun/sqldef/pull/126#issuecomment-865440350 was the answer to it.

2021-06-23 04:45 UTC, ytakaya commented
I changed the way to make a `generateAddIndex` and use `g.mode` in it to branch.

2021-06-25 01:45 UTC, k0kubun approved these changes
:+1: Thanks

2021-06-25 01:45 UTC, merged